# Information
autor: Matheus Castiglioni
baseurl: ""
description: "Documentação do projeto SSearch"
email: matheushcastiglioni@gmail.com
projectname: ssearch
projecturl: https://github.com/mahenrique94/ssearch
title: "SSearch"
url: ssearch.matheuscastiglioni.com.br

# Configuration
collections:
  pages:
    output: true
    permalink: /:name
layout: "page"
static_files: "assets/"
theme: mhc-project-doc